version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-claude_memory}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-claude_memory_pass}
      POSTGRES_DB: ${POSTGRES_DB:-claude_memory}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-claude_memory}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant 向量数据库
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__LOG_LEVEL: INFO

  # Claude Memory 全局服务
  claude-memory:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      # 数据库配置
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-claude_memory}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-claude_memory_pass}
      POSTGRES_DB: ${POSTGRES_DB:-claude_memory}
      
      # Qdrant 配置
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      
      # Claude Memory 配置
      CLAUDE_MEMORY_PROJECT_ID: ${CLAUDE_MEMORY_PROJECT_ID:-global}
      PYTHONUNBUFFERED: 1
      
      # API Keys（从环境变量传入）
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
      - ./.env:/app/.env:ro
    ports:
      - "${API_PORT:-8000}:8000"  # API 端口（如果启用）
    stdin_open: true
    tty: true
    command: ${SERVICE_MODE:-mcp}  # 默认 MCP 模式

  # 可选：API 服务器（独立运行）
  claude-memory-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      # 继承 claude-memory 的环境变量
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-claude_memory}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-claude_memory_pass}
      POSTGRES_DB: ${POSTGRES_DB:-claude_memory}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      CLAUDE_MEMORY_PROJECT_ID: ${CLAUDE_MEMORY_PROJECT_ID:-global}
      PYTHONUNBUFFERED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
      - ./.env:/app/.env:ro
    ports:
      - "${API_PORT:-8000}:8000"
    command: api
    profiles:
      - api  # 只在明确指定时启动

volumes:
  postgres_data:
  qdrant_data: