# Claude Memory MCP 并发优化配置
# 针对高并发访问场景的性能优化配置

# 数据库配置
database:
  url: "sqlite:///global_memory_concurrent.db"
  # PostgreSQL配置示例（生产环境推荐）
  # url: "postgresql://user:password@localhost:5432/claude_memory"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600

# 向量数据库配置
vector_store:
  url: "http://localhost:6333"
  collection_name: "global_memories_concurrent"
  vector_size: 384
  batch_size: 100
  timeout: 30

# 并发优化配置
concurrency:
  # 数据库连接池
  max_connections: 25
  connection_timeout: 10.0
  
  # 内存缓存
  cache_size: 5000
  cache_ttl: 600.0  # 10分钟
  cache_cleanup_interval: 300.0  # 5分钟清理一次
  
  # 线程池
  max_workers: 12
  
  # 批处理配置
  batch_size: 50
  batch_timeout: 5.0
  max_batch_queue_size: 1000
  
  # 请求限流
  rate_limit:
    enabled: true
    max_requests_per_second: 100
    burst_capacity: 200
    
  # 读写锁
  max_concurrent_reads: 50
  max_concurrent_writes: 5

# 记忆管理配置
memory:
  cross_project_sharing: true
  project_isolation: false
  retention_days: 365
  max_conversation_age_days: 90
  auto_cleanup_enabled: true
  cleanup_interval_hours: 24

# 搜索配置
search:
  max_results: 50
  similarity_threshold: 0.7
  enable_semantic_search: true
  semantic_cache_size: 1000
  search_timeout: 10.0
  
  # 全文搜索优化
  fts_enabled: true
  fts_ranking_boost: 1.5
  
  # 结果排序权重
  ranking_weights:
    recency: 0.3
    relevance: 0.5
    project_priority: 0.2

# 性能监控配置
monitoring:
  enabled: true
  metrics_interval: 60  # 秒
  slow_query_threshold: 1.0  # 秒
  log_performance_stats: true
  
  # 性能告警阈值
  alerts:
    high_error_rate: 0.05  # 5%
    high_avg_response_time: 2.0  # 秒
    low_cache_hit_rate: 0.7  # 70%
    connection_pool_exhaustion: 0.9  # 90%使用率

# 健康检查配置  
health_check:
  enabled: true
  interval: 30  # 秒
  timeout: 5  # 秒
  checks:
    - database_connection
    - cache_status
    - vector_store_connection
    - system_resources

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # 性能日志
  performance_logging:
    enabled: true
    sample_rate: 0.1  # 10%采样
    include_query_details: false
    
  # 访问日志
  access_logging:
    enabled: true
    log_file: "logs/access.log"
    rotation: "daily"

# 数据目录配置
data_directories:
  base: "${CLAUDE_MEMORY_DATA:-~/.claude-memory}"
  conversations: "${CLAUDE_MEMORY_DATA:-~/.claude-memory}/conversations"
  cache: "${CLAUDE_MEMORY_DATA:-~/.claude-memory}/cache"
  logs: "${CLAUDE_MEMORY_DATA:-~/.claude-memory}/logs"
  temp: "${CLAUDE_MEMORY_DATA:-~/.claude-memory}/temp"

# 安全配置
security:
  enable_request_validation: true
  max_request_size: "10MB"
  max_query_length: 1000
  rate_limiting_enabled: true
  
  # API密钥配置（如果需要）
  api_key_required: false
  api_key_header: "X-Claude-Memory-Key"

# 开发/调试配置
development:
  debug_mode: false
  profile_requests: false
  enable_test_endpoints: false
  mock_vector_store: false

# 生产环境优化
production:
  # 数据库优化
  database_optimizations:
    enable_query_cache: true
    query_cache_size: "100MB"
    enable_prepared_statements: true
    
  # 系统资源优化
  system_optimizations:
    memory_limit: "2GB"
    cpu_limit: "4"
    disk_cache_size: "500MB"
    
  # 网络优化
  network_optimizations:
    tcp_keepalive: true
    connection_pooling: true
    request_compression: true