global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'claude-memory@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'claude-memory-alerts'

receivers:
  - name: 'claude-memory-alerts'
    webhook_configs:
      - url: 'http://localhost:8081/webhook'
        send_resolved: true

inhibit_rules: []