service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  
storage:
  storage_path: /home/jetgogoing/claude_memory/data/qdrant
  
log_level: INFO

telemetry_disabled: true

cluster:
  enabled: false

# 性能优化配置
hnsw_config:
  max_indexing_threads: 0
  
segment_config:
  max_segment_size_kb: 200000
