# Claude Memory MCP 服务 - Prometheus 配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    service: 'claude-memory-mcp'
    environment: 'production'

# 告警规则文件
rule_files:
  - 'claude_memory_alerts.yml'

# Alertmanager配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# 抓取配置
scrape_configs:
  # Claude Memory MCP 服务指标
  - job_name: 'claude-memory-mcp'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL 导出器（如果已安装）
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    
  # Qdrant 指标
  - job_name: 'qdrant'
    static_configs:
      - targets: ['localhost:6333']
    metrics_path: '/metrics'
    
  # Node Exporter（系统指标）
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
      
  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']